# Generated by AWS Kit Cloud Map from the design design-two-az-vpc.drawio.
# Edits here are overwritten the next time the design is built. Change the design instead.

terraform {
  required_version = ">= 1.6"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 6.0"
    }
  }
}

provider "aws" {
  region = var.region
}

module "lab" {
  source = "../.."

  name_prefix = var.name_prefix
  tags        = var.tags

  vpc = {
    name                 = "lab"
    cidr                 = "10.0.0.0/16"
    enable_dns_hostnames = true
  }
  internet_gateway = "lab-igw"
  subnets = {
    "private-a" = {
      cidr        = "10.0.11.0/24"
      az          = "a"
      public      = false
      route_table = "private-a"
    }
    "private-b" = {
      cidr        = "10.0.12.0/24"
      az          = "b"
      public      = false
      route_table = "private-b"
    }
    "public-a" = {
      cidr        = "10.0.1.0/24"
      az          = "a"
      public      = true
      route_table = "public"
    }
    "public-b" = {
      cidr        = "10.0.2.0/24"
      az          = "b"
      public      = true
      route_table = "public"
    }
  }
  nat_gateways = {
    "nat-a" = {
      subnet = "public-a"
    }
    "nat-b" = {
      subnet = "public-b"
    }
  }
  route_tables = {
    "private-a" = {
      nat_gateway = "nat-a"
    }
    "private-b" = {
      nat_gateway = "nat-b"
    }
    public = {
      internet_gateway = true
    }
  }
  gateway_endpoints = {
    s3 = {
      service      = "s3"
      route_tables = ["private-a", "private-b"]
    }
  }
  security_groups = {
    app = {
      description = "App servers"
    }
    web = {
      description = "Load balancer"
    }
  }
  ingress_rules = {
    "app-tcp-8080-from-web" = {
      security_group            = "app"
      protocol                  = "tcp"
      from_port                 = 8080
      to_port                   = 8080
      referenced_security_group = "web"
    }
    "web-tcp-443-from-0.0.0.0/0" = {
      security_group = "web"
      protocol       = "tcp"
      from_port      = 443
      to_port        = 443
      cidr_ipv4      = "0.0.0.0/0"
    }
  }
  egress_rules = {
    "app-all-to-0.0.0.0/0" = {
      security_group = "app"
      protocol       = "-1"
      cidr_ipv4      = "0.0.0.0/0"
    }
    "web-all-to-0.0.0.0/0" = {
      security_group = "web"
      protocol       = "-1"
      cidr_ipv4      = "0.0.0.0/0"
    }
  }
}
