# Generated by AWS Kit Cloud Map from the design design-two-az-vpc.drawio.
# Edits here are overwritten the next time the design is built. Change the design instead.

output "lab" {
  description = "The lab VPC's IDs."
  value = {
    vpc_id             = module.lab.vpc_id
    subnet_ids         = module.lab.subnet_ids
    security_group_ids = module.lab.security_group_ids
  }
}
