# Generated by AWS Kit Cloud Map from the design design-two-az-vpc.drawio.
# Edits here are overwritten the next time the design is built. Change the design instead.

variable "region" {
  description = "The region to build in. The design was drawn for the one in terraform.tfvars."
  type        = string
}

variable "name_prefix" {
  description = "Goes in front of every Name tag and security group name."
  type        = string
  default     = "two-az-vpc"
}

variable "tags" {
  description = "Tags for every resource."
  type        = map(string)
  default = {
    Design    = "design-two-az-vpc.drawio"
    ManagedBy = "terraform"
  }
}
