# Generated by AWS Kit Cloud Map from the design design-two-az-vpc.drawio.
# Edits here are overwritten the next time the design is built. Change the design instead.

output "vpc_id" {
  description = "The VPC's ID."
  value       = aws_vpc.this.id
}

output "subnet_ids" {
  description = "Subnet IDs by name."
  value       = { for name, subnet in aws_subnet.this : name => subnet.id }
}

output "route_table_ids" {
  description = "Route table IDs by name."
  value       = { for name, table in aws_route_table.this : name => table.id }
}

output "internet_gateway_id" {
  description = "The internet gateway's ID, or null."
  value       = one([for gateway in aws_internet_gateway.this : gateway.id])
}

output "nat_gateway_ids" {
  description = "NAT gateway IDs by name."
  value       = { for name, nat in aws_nat_gateway.this : name => nat.id }
}

output "security_group_ids" {
  description = "Security group IDs by name."
  value       = { for name, group in aws_security_group.this : name => group.id }
}

output "endpoint_ids" {
  description = "VPC endpoint IDs by name."
  value = merge(
    { for name, endpoint in aws_vpc_endpoint.gateway : name => endpoint.id },
    { for name, endpoint in aws_vpc_endpoint.interface : name => endpoint.id },
  )
}
