# Generated by AWS Kit Cloud Map from the design design-two-az-vpc.drawio.
# Edits here are overwritten the next time the design is built. Change the design instead.

variable "name_prefix" {
  description = "Goes in front of every Name tag and security group name."
  type        = string
}

variable "tags" {
  description = "Tags for every resource, on top of its Name tag."
  type        = map(string)
  default     = {}
}

variable "vpc" {
  description = "The VPC: its name, CIDR block, and whether instances get DNS hostnames."
  type = object({
    name                 = string
    cidr                 = string
    enable_dns_hostnames = optional(bool, true)
  })
}

variable "internet_gateway" {
  description = "The internet gateway's name, or null for none."
  type        = string
  default     = null
}

variable "subnets" {
  description = "Subnets by name. az is the zone letter, like a. route_table is a key of route_tables."
  type = map(object({
    cidr        = string
    az          = string
    public      = bool
    route_table = string
  }))
  default = {}
}

variable "nat_gateways" {
  description = "NAT gateways by name, each in a public subnet, with an Elastic IP."
  type = map(object({
    subnet = string
  }))
  default = {}
}

variable "route_tables" {
  description = "Route tables by name. Public ones route 0.0.0.0/0 to the internet gateway, private ones to a NAT gateway."
  type = map(object({
    internet_gateway = optional(bool, false)
    nat_gateway      = optional(string)
  }))
  default = {}
}

variable "gateway_endpoints" {
  description = "Gateway endpoints (s3, dynamodb) by name, and the route tables they're added to."
  type = map(object({
    service      = string
    route_tables = list(string)
  }))
  default = {}
}

variable "interface_endpoints" {
  description = "Interface endpoints by name, with their subnets and security groups."
  type = map(object({
    service         = string
    subnets         = list(string)
    security_groups = optional(list(string), [])
  }))
  default = {}
}

variable "security_groups" {
  description = "Security groups by name."
  type = map(object({
    description = string
  }))
  default = {}
}

variable "ingress_rules" {
  description = "Inbound rules by name. Each allows a CIDR block or another of these security groups."
  type = map(object({
    security_group            = string
    protocol                  = string
    from_port                 = optional(number)
    to_port                   = optional(number)
    cidr_ipv4                 = optional(string)
    cidr_ipv6                 = optional(string)
    referenced_security_group = optional(string)
    description               = optional(string)
  }))
  default = {}
}

variable "egress_rules" {
  description = "Outbound rules by name, the same way as ingress_rules."
  type = map(object({
    security_group            = string
    protocol                  = string
    from_port                 = optional(number)
    to_port                   = optional(number)
    cidr_ipv4                 = optional(string)
    cidr_ipv6                 = optional(string)
    referenced_security_group = optional(string)
    description               = optional(string)
  }))
  default = {}
}
