# Generated by AWS Kit Cloud Map from the design design-two-az-vpc.drawio.
# Edits here are overwritten the next time the design is built. Change the design instead.

terraform {
  required_version = ">= 1.6"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 6.0"
    }
  }
}
